export const projectData = [
  {
    img: "./images/mtn.jpg",
    title: "Movie to Night",
    techs: ["react", "sass"],
    gh: "https://github.com/cviterales/movie-to-night",
    demo: "https://cviterales.github.io/movie-to-night/#/",
  },
  {
    img: "./images/ag.png",
    title: "Autogestión",
    techs: ["angular", "typescript", "redux", "sass", "nodejs", "express", "mysql"],
    gh: "https://autogestion.batan.coop/#/",
    demo: "https://autogestion.batan.coop/#/",
  },
  {
    img: "./images/tmc.png",
    title: "Task Manager",
    techs: [
      "react",
      "redux",
      "sass",
      "nodejs",
      "express",
      "mysql",
      "socketio",
    ],
    gh: "https://github.com/cviterales/task-manager",
    demo: "http://181.41.240.26",
  },
  {
    img: "./images/btv.png",
    title: "Batan TV",
    techs: ["react", "redux", "sass", "nodejs", "express", "mongodb"],
    gh: "https://github.com/cviterales/batan-tv",
    demo: "https://batan.tv/#/",
  },
  {
    img: "./images/mn.png",
    title: "Monitor",
    techs: [
      "react",
      "redux",
      "css3",
      "nodejs",
      "express",
      "mysql",
      "socketio",
    ],
    gh: "https://github.com/franngette/monitor-front-end",
    demo: "https://github.com/franngette/monitor-front-end",
  },
  {
    img: "./images/sh.png",
    title: "Shop App",
    techs: ["react native", "redux", "firebase"],
    gh: "https://github.com/cviterales/the-shop-app",
    demo: "https://github.com/cviterales/the-shop-app",
  },
];